### ISSUE TITLE
Read and Write plugin error

### ISSUE THREAD

**Issue by krutz89** [bkromhout/Read_and_Write_Excel_Modified#4]
Hi, after installing Read_and_Write_Excel, I am running into an Exception: 
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 111MB of 12013MB (<1%)
 
java.io.FileNotFoundException: C:\Users\SN7157\Desktop\Rename me after writing is done.xlsx (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at Read_and_Write_Excel$ExcelHolder.ensureExcelFileExists(Read_and_Write_Excel.java:382)
	at Read_and_Write_Excel$ExcelHolder.readFileAndOpenWorkbook(Read_and_Write_Excel.java:363)
	at Read_and_Write_Excel.run(Read_and_Write_Excel.java:135)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

I am trying to export my results table into the excel sheet. My goal is to create a macros for 1000s images who's plot values are populated into results table and export the data in the excel file. 

I am able to successfully rename plot values table to results. But when running "Read and Write Excel" from plugin, the results do not populate into an excel file, and I see the above exception table. 

Is there a way I can fix this? I am currently on Windows 10 Enterprise and Using Office 365 ProPlus. Is this plugin compatible with the config?

**Comment by Thecatinamustang** [comment]
same issue here:

(Fiji Is Just) ImageJ 2.3.0/1.53q; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 233MB of 12097MB (1%)
 
java.io.FileNotFoundException: C:\Users\Katja\Desktop\Rename me after writing is done.xlsx (Das System kann den angegebenen Pfad nicht finden)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at Read_and_Write_Excel$ExcelHolder.ensureExcelFileExists(Read_and_Write_Excel.java:382)
	at Read_and_Write_Excel$ExcelHolder.readFileAndOpenWorkbook(Read_and_Write_Excel.java:363)
	at Read_and_Write_Excel.run(Read_and_Write_Excel.java:135)
	at ij.IJ.runUserPlugIn(IJ.java:243)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:67)
	at java.lang.Thread.run(Thread.java:750)

...i am running on Win 11.
